format = """
[░▒▓](#2A2A37)\
$os\
[](bg:#8BAE5A fg:#2A2A37)\
$directory\
[](fg:#8BAE5A bg:#3B3B4F)\
$git_branch\
$git_status\
[](fg:#3B3B4F bg:#2A2A37)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2A2A37 bg:#16161D)\
$time\
[ ](fg:#16161D)\
\n$character"""

# ================= OS =================
[os]
disabled = false
style = "bg:#2A2A37 fg:#DCD7BA"
format = "[ $symbol ]($style)"

[os.symbols]
Macos = "[](fg:#7E9CD8 bg:#2A2A37)"
Linux = "[  ](fg:#a3aed2 bg:#2A2A37)"
Ubuntu = "[  ](fg:#a3aed2 bg:#2A2A37)"
Debian = "[  ](fg:#a3aed2 bg:#2A2A37)"
Arch = "[  ](fg:#a3aed2 bg:#2A2A37)"
Manjaro = "[  ](fg:#a3aed2 bg:#2A2A37)"
Fedora = "[  ](fg:#a3aed2 bg:#2A2A37)"
NixOS = "[  ](fg:#a3aed2 bg:#2A2A37)"
Windows = "[  ](fg:#a3aed2 bg:#2A2A37)"

# ================= DIRECTORY =================
[directory]
style = "fg:#16161D bg:#8BAE5A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# ================= GIT =================
[git_branch]
symbol = ""
style = "bg:#3B3B4F"
format = '[[ $symbol $branch ](fg:#E6C384 bg:#3B3B4F)]($style)'

[git_status]
style = "bg:#3B3B4F"
format = '[[($all_status$ahead_behind )](fg:#E6C384 bg:#3B3B4F)]($style)'

# ================= LANGUAGES =================
[nodejs]
symbol = ""
style = "bg:#2A2A37"
format = '[[ $symbol ($version) ](fg:#98BB6C bg:#2A2A37)]($style)'

[rust]
symbol = ""
style = "bg:#2A2A37"
format = '[[ $symbol ($version) ](fg:#FF9E3B bg:#2A2A37)]($style)'

[golang]
symbol = ""
style = "bg:#2A2A37"
format = '[[ $symbol ($version) ](fg:#7AA89F bg:#2A2A37)]($style)'

[php]
symbol = ""
style = "bg:#2A2A37"
format = '[[ $symbol ($version) ](fg:#957FB8 bg:#2A2A37)]($style)'

# ================= TIME =================
[time]
disabled = false
time_format = "%R"
style = "bg:#16161D"
format = '[[  $time ](fg:#DCD7BA bg:#16161D)]($style)'
